name: Push to pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
        
      - name: Install and Build
        run: |
          npm install
          npm run build
          ls | grep -v "public" | xargs rm -rf
          cd public
          mv -v * ..
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: .
          CLEAN: true

      - name: Notify
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: Gara
          color: '#181b21'
          avatarUrl: https://i.imgur.com/FYRnwoh.jpg
          description: Deploy complete. ([Site here](https://0x20F.github.io/xtype))
          footer: ${{ github.sha }}
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
